call plug#begin()
Plug 'junegunn/vim-easy-align'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }

Plug 'tpope/vim-surround'
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-commentary'

Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

Plug 'morhetz/gruvbox'

Plug 'preservim/nerdtree'

Plug 'neoclide/coc.nvim', {'branch': 'release'}

Plug 'nvim-treesitter/nvim-treesitter'

Plug 'jiangmiao/auto-pairs'

Plug 'mattn/emmet-vim'

Plug 'luochen1990/rainbow'
call plug#end()

" general
set nu rnu
let mapleader = " "
set so=5
set backspace=indent,eol,start
set mouse=a

" colorscheme
colorscheme gruvbox
let g:rainbow_active = 1

" tabs vs spaces
set tabstop=4
set shiftwidth=4
set expandtab

" airline
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#left_sep = ' '
let g:airline#extensions#tabline#left_alt_sep = '|'

" move with option (alt on mac)
nnoremap <A-j> :m .+1<CR>==
nnoremap <A-k> :m .-2<CR>==
vnoremap <A-j> :m '>+1<CR>gv=gv
vnoremap <A-k> :m '<-2<CR>gv=gv

" nerd tree
nnoremap <leader>e :NERDTreeToggle<CR>

" change cursor based on mode
autocmd InsertEnter * set cul
autocmd InsertLeave * set nocul

" navigate buffers
noremap <C-j> <C-W>j
noremap <C-k> <C-W>k
noremap <C-h> <C-W>h
noremap <C-l> <C-W>l
