path+="$HOME/bin:/usr/local/bin"
path+="/Users/olem/.cargo/bin"
path+="$HOME/.emacs.d/bin"
path+="/usr/local/sbin"
path+="/usr/local/opt/openjdk/bin"
path+="/Library/Frameworks/Python.framework/Versions/3.10/bin"
path+="$HOME/.local/bin"
path+="/opt/homebrew/opt/openjdk/bin"
path+="$BUN_INSTALL/bin"
path+="/opt/homebrew/opt/llvm@12/bin"
path+="/opt/homebrew/opt/node@16/bin"
export PATH

# Java homebrew

export CPPFLAGS="-I/opt/homebrew/opt/openjdk/include"

plugins=(
    git 
    zsh-syntax-highlighting
    zsh-fzf-history-search
)

export ZSH="$HOME/.oh-my-zsh"
source $ZSH/oh-my-zsh.sh

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# Aliases

## Better ls

alias l="exa"
alias ls="exa"
alias la="exa -a"
alias ll="exa -l"
alias lla="exa -la"

alias v="nvim"
alias vi="nvim"
alias vim="nvim"

alias cat="bat"

## Cargo

export CARGO_NAME="Ole Magnus Johnsen"
export CARGO_EMAIL="ole.magnus@me.com"

## To folders

export DOTFILES="$HOME/Documents/github/dotfiles"
alias echodb="psql -h $(ifconfig -u | grep 'inet ' | grep -v 127.0.0.1 | cut -d\  -f2 | head -1) -p 5432 -U postgres"
alias front="cd $HOME/Documents/github/echo-web/frontend"
alias back="cd $HOME/Documents/github/echo-web/backend"
alias github="cd $HOME/Documents/github/"
alias dots="cd $DOTFILES"

# Start starship

eval "$(starship init zsh)"

# Fzf

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Use node 16 as default

export LDFLAGS="-L/opt/homebrew/opt/node@16/lib"
export CPPFLAGS="-I/opt/homebrew/opt/node@16/include"

# Haskell

[ -f "/Users/olem/.ghcup/env" ] && source "/Users/olem/.ghcup/env" # ghcup-env

# Bun

[ -s "/Users/olem/.bun/_bun" ] && source "/Users/olem/.bun/_bun"
export BUN_INSTALL="/Users/olem/.bun"

