path+="$HOME/bin:/usr/local/bin"
path+="/Users/olem/.cargo/bin"
path+="$HOME/.emacs.d/bin"
path+="/usr/local/sbin"
path+="/usr/local/opt/openjdk/bin"
path+="/Library/Frameworks/Python.framework/Versions/3.10/bin"
path+="$HOME/.local/bin"
path+="/opt/homebrew/opt/openjdk/bin"
export PATH

# Java homebrew
export CPPFLAGS="-I/opt/homebrew/opt/openjdk/include"

plugins=(
    git 
    zsh-syntax-highlighting
    web-search
    zsh-fzf-history-search
)

export ZSH="$HOME/.oh-my-zsh"
source $ZSH/oh-my-zsh.sh

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# Aliases
#
## Better ls
alias l="exa"
alias ls="exa"
alias la="exa -a"
alias ll="exa -l"
alias lla="exa -la"

## Cargo
export CARGO_NAME="Ole Magnus Johnsen"
export CARGO_EMAIL="ole.magnus@me.com"xport inf142="$uib/semester2/inf142"

## To folders
export DOTFILES=$HOME/Documents/github/configs


eval "$(starship init zsh)"

export HOMEBREW_AUTO_UPDATE_SECS="86400"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

[ -f "/Users/olem/.ghcup/env" ] && source "/Users/olem/.ghcup/env" # ghcup-env
export GPG_TTY=$(tty)
export PATH="/opt/homebrew/opt/node@16/bin:$PATH"
