# CodeWhisperer pre block. Keep at the top of this file.
[[ -f "${HOME}/Library/Application Support/codewhisperer/shell/zshrc.pre.zsh" ]] && builtin source "${HOME}/Library/Application Support/codewhisperer/shell/zshrc.pre.zsh"

# setup zap
[ -f "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh" ] && source "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh"

# zap plugins
plug "zap-zsh/supercharge"
plug "zsh-users/zsh-syntax-highlighting"
plug "joshskidmore/zsh-fzf-history-search"

GOPATH="$HOME/go"

# PATH
path+="$HOME/.ghcup/bin"
path+="$HOME/.cargo/bin"
path+="$HOME/.emacs.d/bin"
path+="$HOME/.local/bin"
path+="$HOME/.deno/bin"
path+="$GOPATH/bin"

path+="/usr/local/bin"
path+="/usr/local/sbin"
path+="/usr/local/opt/openjdk/bin"

path+="$BUN_INSTALL/bin"

path+="$HOME/.composer/vendor/bin"

path+="/Library/Frameworks/Python.framework/Versions/3.10/bin"

path+="/opt/homebrew/opt/openjdk/bin"
path+="/opt/homebrew/opt/llvm/bin"
#path+="/opt/homebrew/opt/node@16/bin"
path+="/opt/homebrew/opt/postgresql@15/bin"
path+="/opt/homebrew/opt/openjdk@17/bin"
path+="/opt/homebrew/opt/sqlite/bin"

path+="/Users/olem/Library/Caches/fnm_multishells/86204_1710421977269/bin"

export PATH

# ZSH
export ZSH="$HOME/.oh-my-zsh"
source $ZSH/oh-my-zsh.sh

# iTerm
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# EDITOR
export EDITOR="nvim"

# Aliases

alias l="eza"
alias ls="eza"
alias la="eza -a"
alias ll="eza -l"
alias lla="eza -la"

alias i="pnpm i"

alias cat="bat"

alias cd="z"

alias uib="cd $HOME/Google\ Drive/My\ Drive/uib/"

alias ass2="cd /Applications/XAMPP/htdocs/inf115"

alias minecraft="cd $HOME/Library/Application\ Support/minecraft"

## Cargo
export CARGO_NAME="Ole Magnus Johnsen"
export CARGO_EMAIL="ole.magnus@me.com"

## To folders
export PROGRAMMING="$HOME/Programming/"
export DOTFILES="$PROGRAMMING/github/dotfiles"
alias front="cd $PROGRAMMING/github/echo-web/frontend"
alias back="cd $PROGRAMMING/github/echo-web/backend"
alias mono="cd $PROGRAMMING/github/new-website"
alias dots="cd $DOTFILES"
alias conf="cd $HOME/.config"

## Docker
alias dcu="docker-compose up --build"
alias dcd="docker-compose down"

# Start starship
eval "$(starship init zsh)"

# Start zoxide
eval "$(zoxide init zsh)"

# Fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Flags

## LLVM
LDFLAGS+="-L$(brew --prefix)/opt/llvm/lib -Wl,-rpath,$(brew --prefix)/opt/llvm/lib"
LDFLAGS+="-L/opt/homebrew/opt/node@16/lib"
export LDFLAGS

## CPP
CPPFLAGS+="-I/opt/homebrew/opt/llvm/include"
CPPFLAGS+="-I/opt/homebrew/opt/openjdk/include"
CPPFLAGS+="-I/opt/homebrew/opt/node@16/include"
export CPPFLAGS

# GHCUP
[ -f "/Users/olem/.ghcup/env" ] && source "/Users/olem/.ghcup/env"

# Bun
[ -s "/Users/olem/.bun/_bun" ] && source "/Users/olem/.bun/_bun"
export BUN_INSTALL="/Users/olem/.bun"

# Heroku
HEROKU_AC_ZSH_SETUP_PATH=/Users/olem/Library/Caches/heroku/autocomplete/zsh_setup && test -f $HEROKU_AC_ZSH_SETUP_PATH && source $HEROKU_AC_ZSH_SETUP_PATH;

# tabtab source for packages
# uninstall by removing these lines
[[ -f ~/.config/tabtab/zsh/__tabtab.zsh ]] && . ~/.config/tabtab/zsh/__tabtab.zsh || true


# pnpm
export PNPM_HOME="/Users/olem/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

# fnm
export FNM_LOGLEVEL="info"
export FNM_ARCH="arm64"
export FNM_VERSION_FILE_STRATEGY="local"
export FNM_COREPACK_ENABLED="false"
export FNM_RESOLVE_ENGINES="false"
export FNM_MULTISHELL_PATH="/Users/olem/Library/Caches/fnm_multishells/86204_1710421977269"
export FNM_NODE_DIST_MIRROR="https://nodejs.org/dist"
export FNM_DIR="/Users/olem/Library/Application Support/fnm"
rehash

# Change zsh-syntax-highlight color
ZSH_HIGHLIGHT_STYLES[arg0]="fg=blue,bold"
ZSH_HIGHLIGHT_STYLES[alias]="fg=magenta,bold"
ZSH_HIGHLIGHT_STYLES[precommand]="fg=blue,bold,underline"

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /opt/homebrew/bin/terraform terraform

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# opam configuration
[[ ! -r /Users/olem/.opam/opam-init/init.zsh ]] || source /Users/olem/.opam/opam-init/init.zsh  > /dev/null 2> /dev/null


[[ -f "$HOME/fig-export/dotfiles/dotfile.zsh" ]] && builtin source "$HOME/fig-export/dotfiles/dotfile.zsh"

# CodeWhisperer post block. Keep at the bottom of this file.
[[ -f "${HOME}/Library/Application Support/codewhisperer/shell/zshrc.post.zsh" ]] && builtin source "${HOME}/Library/Application Support/codewhisperer/shell/zshrc.post.zsh"
