# Add deno completions to search path
if [[ ":$FPATH:" != *":/Users/olem/.zsh/completions:"* ]]; then export FPATH="/Users/olem/.zsh/completions:$FPATH"; fi
# setup zap
[ -f "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh" ] && source "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh"

# zap plugins
plug "zap-zsh/supercharge"
plug "zsh-users/zsh-syntax-highlighting"
plug "joshskidmore/zsh-fzf-history-search"

bindkey -e

GOPATH="$HOME/go"

# PATH
path+="$HOME/.ghcup/bin"
path+="$HOME/.cargo/bin"
path+="$HOME/.emacs.d/bin"
path+="$HOME/.local/bin"
path+="$HOME/.deno/bin"
path+="$GOPATH/bin"

path+="/usr/local/bin"
path+="/usr/local/sbin"
path+="/usr/local/opt/openjdk/bin"

path+="$BUN_INSTALL/bin"

path+="$HOME/.composer/vendor/bin"

path+="/Library/Frameworks/Python.framework/Versions/3.10/bin"

path+="/opt/homebrew/opt/openjdk/bin"
path+="/opt/homebrew/opt/llvm/bin"
path+="/opt/homebrew/opt/postgresql@15/bin"
path+="/opt/homebrew/opt/openjdk@17/bin"
path+="/opt/homebrew/opt/sqlite/bin"
path+="/opt/homebrew/opt/rustup/bin"

path+="/Library/Developer/CommandLineTools/usr/bin"

export PATH

# EDITOR
export EDITOR="nvim"

# Aliases

alias l="eza"
alias ls="eza"
alias la="eza -a"
alias ll="eza -l"
alias lla="eza -la"

alias i="pnpm i"
alias cat="bat"
alias cd="z"
alias uib="cd $HOME/Google\ Drive/My\ Drive/uib/"
alias minecraft="cd $HOME/Library/Application\ Support/minecraft"

# dot dot dot
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ......="cd ../../../../.."
alias .......="cd ../../../../../.."
alias ........="cd ../../../../../../.."

## Cargo
export CARGO_NAME="Ole Magnus Johnsen"
export CARGO_EMAIL="ole.magnus@me.com"

export XDG_CONFIG_HOME="$HOME/.config"

## To folders
export PROGRAMMING="$HOME/Developer"
export DOTFILES="$PROGRAMMING/github/dotfiles"
alias front="cd $PROGRAMMING/github/echo-web/frontend"
alias back="cd $PROGRAMMING/github/echo-web/backend"
alias mono="cd $PROGRAMMING/github/new-website"
alias dots="cd $DOTFILES"
alias conf="cd $HOME/.config"

## Docker
alias dcu="docker-compose up --build"
alias dcd="docker-compose down"

# Start starship
eval "$(starship init zsh)"

# Start zoxide
eval "$(zoxide init zsh)"

# Fzf
source <(fzf --zsh)


# GHCUP
[ -f "/Users/olem/.ghcup/env" ] && source "/Users/olem/.ghcup/env"

# fnm
eval "$(fnm env --use-on-cd --shell zsh)"

# tabtab source for packages
# uninstall by removing these lines
[[ -f ~/.config/tabtab/zsh/__tabtab.zsh ]] && . ~/.config/tabtab/zsh/__tabtab.zsh || true

# pnpm
export PNPM_HOME="/Users/olem/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

# Change zsh-syntax-highlight color
ZSH_HIGHLIGHT_STYLES[arg0]="fg=blue,bold"
ZSH_HIGHLIGHT_STYLES[alias]="fg=magenta,bold"
ZSH_HIGHLIGHT_STYLES[precommand]="fg=blue,bold,underline"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

export PATH="/Applications/MacPorts/Emacs.app/Contents/MacOS:$PATH"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR=$(brew --prefix sdkman-cli)/libexec
[[ -s "${SDKMAN_DIR}/bin/sdkman-init.sh" ]] && source "${SDKMAN_DIR}/bin/sdkman-init.sh"

export PATH="/Users/olem/.config/herd-lite/bin:$PATH"
export PHP_INI_SCAN_DIR="/Users/olem/.config/herd-lite/bin:$PHP_INI_SCAN_DIR"
. "/Users/olem/.deno/env"

# bun completions
[ -s "/Users/olem/.bun/_bun" ] && source "/Users/olem/.bun/_bun"

alias claude="/Users/olem/.claude/local/claude"
