# Fig pre block. Keep at the top of this file.
[[ -f "$HOME/.fig/shell/zshrc.pre.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.pre.zsh"
plugins=(
    git 
    zsh-syntax-highlighting
    zsh-fzf-history-search
)

# PATH

path+="$HOME/.ghcup/bin"
path+="$HOME/.cargo/bin"
path+="$HOME/.emacs.d/bin"
path+="$HOME/.local/bin"

path+="/usr/local/bin"
path+="/usr/local/sbin"
path+="/usr/local/opt/openjdk/bin"

path+="$BUN_INSTALL/bin"

path+="/Library/Frameworks/Python.framework/Versions/3.10/bin"

path+="/opt/homebrew/opt/openjdk/bin"
path+="/opt/homebrew/opt/llvm/bin"
#path+="/opt/homebrew/opt/node@16/bin"

export PATH

# ZSH

export ZSH="$HOME/.oh-my-zsh"
source $ZSH/oh-my-zsh.sh

# nvm

export NVM_DIR="$HOME/.nvm"
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

# iTerm

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# EDITOR

export EDITOR="vim"

# Aliases

## Better ls

alias l="exa"
alias ls="exa"
alias la="exa -a"
alias ll="exa -l"
alias lla="exa -la"

alias cat="bat"

alias uib="cd $HOME/Google\ Drive/My\ Drive/uib/"

## Cargo

export CARGO_NAME="Ole Magnus Johnsen"
export CARGO_EMAIL="ole.magnus@me.com"

## To folders

export DOTFILES="$HOME/Programming/github/dotfiles"
alias front="cd $HOME/Programming/github/echo-web/frontend"
alias back="cd $HOME/Programming/github/echo-web/backend"
alias github="cd $HOME/Programming/github/"

alias dots="cd $DOTFILES"

## Docker

alias dcu="docker-compose up --build"
alias dcd="docker-compose down"

# Start starship

eval "$(starship init zsh)"

# Fzf

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Flags

## LLVM

LDFLAGS+="-L$(brew --prefix)/opt/llvm/lib -Wl,-rpath,$(brew --prefix)/opt/llvm/lib"
LDFLAGS+="-L/opt/homebrew/opt/node@16/lib"
export LDFLAGS

## CPP

CPPFLAGS+="-I/opt/homebrew/opt/llvm/include"
CPPFLAGS+="-I/opt/homebrew/opt/openjdk/include"
CPPFLAGS+="-I/opt/homebrew/opt/node@16/include"
export CPPFLAGS

# GHCUP

[ -f "/Users/olem/.ghcup/env" ] && source "/Users/olem/.ghcup/env"

# Bun

[ -s "/Users/olem/.bun/_bun" ] && source "/Users/olem/.bun/_bun"
export BUN_INSTALL="/Users/olem/.bun"

# Heroku

HEROKU_AC_ZSH_SETUP_PATH=/Users/olem/Library/Caches/heroku/autocomplete/zsh_setup && test -f $HEROKU_AC_ZSH_SETUP_PATH && source $HEROKU_AC_ZSH_SETUP_PATH;

# tabtab source for packages
# uninstall by removing these lines
[[ -f ~/.config/tabtab/zsh/__tabtab.zsh ]] && . ~/.config/tabtab/zsh/__tabtab.zsh || true

export PATH="/opt/homebrew/opt/postgresql@15/bin:$PATH"

# Fig post block. Keep at the bottom of this file.
[[ -f "$HOME/.fig/shell/zshrc.post.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.post.zsh"

# pnpm
export PNPM_HOME="/Users/olem/Library/pnpm"
export PATH="$PNPM_HOME:$PATH"
# pnpm end