#!/bin/sh

# Autostart
#pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd &
nm-applet &
lxpolkit &
$HOME/.config/polybar/launch.sh
$HOME/.fehbg 
picom --experimental-backends &
xss-lock betterlockscreen -l blur -- suspend &
pgrep bspswallow || bspswallow &

# Workspaces
bspc monitor -d I II III IV V VI VII

# Border
bspc config border_width         3
#bspc config focused_border_color "#00498D"

# Split
bspc config split_ratio 0.52

# Viewing options
bspc config borderless_monocle    false
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

# Padding and gap
bspc config top_padding 35 # Polybarheight + window_gap
bspc config window_gap  10

# Window rules
bspc rule -a Blueman-manager state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a inf101v22-tetris-TetrisMain state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

