#"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
format = """
$username$hostname$directory$git_branch$git_status$package$time
$character"""

[git_metrics]
disabled = false

[time]
disabled = false
format = "at [$time]($style) "
time_format = "%H:%M:%S"
style = "bold yellow"

[directory]
style = "bold blue"
read_only = " "
truncation_length = 3
truncate_to_repo = true

[git_branch]
style = "bold blue"

[character]
success_symbol = "[λ](bold blue)"
error_symbol = "[λ](bold red)"

[memory_usage]
symbol = " "

[aws]
disabled = true

[gcloud]
disabled = true
