#!/bin/sh

# Autostart
sxhkd &
#nm-applet &
lxpolkit &
pgrep polybar || $HOME/.config/polybar/launch.sh
$HOME/.fehbg 
pgrep emacs || emacs --daemon &
picom --experimental-backends &
pgrep bspswallow || bspswallow &
xsetroot -cursor_name left_ptr &
mount-drives

# For artix
#xss-lock betterlockscreen -l blur -- suspend &

# Workspaces
bspc monitor -d I II III IV V VI VII

# Border
bspc config border_width         3
bspc config focused_border_color "#777777"

# Split
bspc config split_ratio 0.52

# Viewing options
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

# Padding and gap
bspc config top_padding 40 # Polybarheight + window_gap
bspc config window_gap  10

# Window rules
bspc rule -a 1Password state=floating
bspc rule -a Blueman-manager state=floating

