#!/bin/sh

# Autostart
sxhkd &
#nm-applet &
lxpolkit &
$HOME/.config/polybar/launch.sh
$HOME/.fehbg 
pgrep emacs || emacs --daemon &
picom --experimental-backends &
pgrep bspswallow || bspswallow &
xsetroot -cursor_name left_ptr &

# For artix
#xss-lock betterlockscreen -l blur -- suspend &

if [[ $(xrandr -q | grep 'HDMI-1 connected') ]]; then
	xrandr --output HDMI-1 --primary --mode 1920x1080 --rotate normal --output eDP-1 --mode 1920x1080 --rotate normal

	bspc monitor eDP-1  -d I II III IV V VI VII
	bspc monitor HDMI-1 -d I II III IV V VI VII
else
	xrandr --output eDP-1 --primary --mode 1920x1080 --rotate normal
	bspc monitor -d I II III IV V VI VII
fi

# Border
bspc config border_width         3
bspc config focused_border_color "#777777"

# Split
bspc config split_ratio 0.52

# Viewing options
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

# Padding and gap
bspc config top_padding 42 # Polybarheight + window_gap
bspc config window_gap  8

# Window rules
bspc rule -a 1Password state=floating
bspc rule -a Blueman-manager state=floating

