# setup zap
[ -f "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh" ] && source "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh"

# zap plugins
plug "zap-zsh/supercharge"
plug "zsh-users/zsh-syntax-highlighting"
plug "joshskidmore/zsh-fzf-history-search"

bindkey -e

# PATH
path+="$HOME/.cargo/bin"
path+="$HOME/.local/bin"

path+="/usr/local/bin"
path+="/usr/local/sbin"

path+="/Library/Developer/CommandLineTools/usr/bin"

export PATH

# EDITOR
export EDITOR="nvim"

# Aliases

alias l="eza"
alias ls="eza"
alias la="eza -a"
alias ll="eza -l"
alias lla="eza -la"

alias i="pnpm i"
alias cat="bat"
alias cd="z"

# dot dot dot
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ......="cd ../../../../.."
alias .......="cd ../../../../../.."
alias ........="cd ../../../../../../.."

export XDG_CONFIG_HOME="$HOME/.config"

## To folders
export PROGRAMMING="$HOME/Developer"
export DOTFILES="$PROGRAMMING/github/dotfiles"
alias dots="cd $DOTFILES"
alias conf="cd $HOME/.config"

# Start starship
eval "$(starship init zsh)"

# Start zoxide
eval "$(zoxide init zsh)"

# Fzf
source <(fzf --zsh)

# fnm
eval "$(fnm env --use-on-cd --shell zsh)"

# pnpm
export PNPM_HOME="/Users/ole/Library/pnpm"
case ":$PATH:" in
*":$PNPM_HOME:"*) ;;
*) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

# Change zsh-syntax-highlight color
ZSH_HIGHLIGHT_STYLES[arg0]="fg=blue,bold"
ZSH_HIGHLIGHT_STYLES[alias]="fg=magenta,bold"
ZSH_HIGHLIGHT_STYLES[precommand]="fg=blue,bold,underline"

alias claude="/Users/olem/.claude/local/claude"
