call plug#begin()
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'junegunn/vim-easy-align'
Plug 'junegunn/fzf.vim'
Plug 'nvim-lua/plenary.nvim'
Plug 'luochen1990/rainbow'
Plug 'liuchengxu/vim-clap', { 'do': ':Clap install-binary' }
Plug 'preservim/nerdtree'
Plug 'tpope/vim-commentary'
Plug 'ntpeters/vim-better-whitespace'
Plug 'mattn/emmet-vim'
Plug 'ap/vim-css-color'
Plug 'tpope/vim-sensible'
Plug 'prettier/vim-prettier', { 'do': 'yarn install --frozen-lockfile --production' }
Plug 'tpope/vim-sleuth'
Plug 'rust-lang/rust.vim'
Plug 'tomasiser/vim-code-dark'
call plug#end()

" Settings
let mapleader = " "
colorscheme codedark
set backspace=indent,eol,start
set nu rnu
set mouse=a
set so=5

" Prettier
filetype plugin indent on
let g:prettier#autoformat = 1
let g:prettier#autoformat_require_pragma = 0

" Whitespace highlight
let g:better_whitespace_enabled=1

" Color brackets
let g:rainbow_active = 1

" Prettier
nmap <Leader>py <Plug>(Prettier)

" Airline
let g:airline#extensions#tabline#enabled = 1
let g:airline#enable#bufferline=1

" Nerdtree
nnoremap <leader>e :NERDTreeToggle<CR>

" Window Navigation with Ctrl-[hjkl]
noremap <C-J> <C-W>j
noremap <C-K> <C-W>k
noremap <C-H> <C-W>h
noremap <C-L> <C-W>l

""" Notes
" gc - comment out line in visual mode
