" Settings
let mapleader = " "
set backspace=indent,eol,start
set nu rnu
set mouse=a
set so=5

" Write and quit
nnoremap <leader>qq :q<CR>

" Window Navigation with Ctrl-[hjkl]
noremap <C-J> <C-W>j
noremap <C-K> <C-W>k
noremap <C-H> <C-W>h
noremap <C-L> <C-W>l

