plugins=(
    git 
    zsh-syntax-highlighting
    web-search
    zsh-fzf-history-search
)

# PATH

path+="$HOME/bin"
path+="$HOME/.cargo/bin"
path+="$HOME/.yarn/bin"
path+="$HOME/.local/bin"

path+="/usr/local/bin"

export PATH

# ZSH

export ZSH="$HOME/.oh-my-zsh"
source $ZSH/oh-my-zsh.sh

# Aliases

alias l="exa"
alias ls="exa"
alias la="exa -a"
alias ll="exa -l"
alias lla="exa -la"

alias v="lvim"

alias dots="cd $DOTFILES"

alias uib="cd $HOME/Google\ Drive/uib"

# Folders

export DOTFILES=$HOME/Documents/github/dotfiles

# Cargo

export CARGO_NAME="Ole Magnus Johnsen"
export CARGO_EMAIL="ole.magnus@me.com"

# Starship

eval "$(starship init zsh)"

# Fzf

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# GHCup

[ -f "/home/olem/.ghcup/env" ] && source "/home/olem/.ghcup/env" # ghcup-env
